export const CONSTANT = {
  TOAST_SUCCESS_MSG: {
    CREATE: "Data created successfully",
    UPDATE: "Data updated successfully",
    DELETE: "Data deleted successfully",
    FETCH: "Data fetched successfully",
    LOGOUT: "User LogOut successfully",
    LOGIN: "User LogIn successfully",
    FILE_DOWNLOADED: "File Downloaded successfully",
    COMMENT_ADDED: "Comment Added",
  },
  TOAST_ERROR_MSG: {
    NETWORK: "Network error, please try again",
    NOT_FOUND: "Data not found",
    COMMON: "Something Went Wrong!",
    LARGE_FILE: "File Is Too Large",
    DATA_NOT_SELECTED: "Please Select a Data",
    PREVIEW_FAIL: "File Preview Fail",
  },
  TOAST_WARNING_MSG: {
    LARGE_IMAGE_FILE: "File Size Must Be Under 5 MB",
    LARGE_VIDEO_FILE: "File Size Must Be Under 10 MB",
    INVALID_FILE_TYPE: "InValide File Type",
  },
  MIME_TYPES: {
    IMAGE: ["image/jpg", "image/png", "image/jpeg", "image/webp"],
    PDF: "application/pdf",
    EXCEL: [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-excel",
    ],
    VIDEO: [
      "video/mp4",
      "video/webm",
      "video/ogg",
      "video/x-matroska",
      "video/mkv",
      "video/matroska",
    ],
    TXT: "text/plain",
  },
  VALIDATION: {
    EMAIL: "Email is required!",
    FIRSTNAME: "First Name is required!",
    LASTNAME: "Last Name is required!",
    FULLNAME: "Full Name is required!",
    PHONENUMBER: "Phone Number is required!",
    ALTERNATEPHONENUMBER: "Alternate Phone Number is required!",
    GENDER: "Gender is required!",
    DATEOFBIRTH: "Date of Birth is required!",
    COMPANYNAME: "Company Name is required!",
    DEPARTMENT: "Department is required!",
    DESIGNATION: "Designation is required!",
    EMPLOYEEID: "Employee ID is required!",
    CITY: "City is required!",
    STATE: "State is required!",
    COUNTRY: "Country is required!",
    ZIPCODE: "Zipcode is required!",
    DISTRICT: "District is required!",
    USERNAME: "Username is required!",
    PASSWORD: "Password is required!",
    CONFIRMPASSWORD: "Confirm Password is required!",
    WEBSITE: "Website is required!",
    DESCRIPTION: "Description is required!",
    NOTES: "Notes are required!",
    STATUS: "Status is required!",
    PROFILEIMAGE: "Profile Image is required!",
    CREATEDBY: "Created By is required!",
    UPDATEDBY: "Updated By is required!",
  },
  MAX_FILE_SIZE: {
    SMALL: 5 * 1024 * 1024,
    LARGE: 10 * 1024 * 1024,
  },
  HOME_PAGE_TABLE_HEADER: [
    { key: "srNo", label: "Sr.No" },
    { key: "name", label: "Name" },
    { key: "age", label: "Age" },
    { key: "birthdate", label: "BirthDate" },
    { key: "uploadFile", label: "Image Preview" },
    { key: "operation", label: "Operations" },
  ],
  USER_EXPENSE_TABLE_HEADER: [
    { key: "employeeName", label: "Employee Name" },
    { key: "category", label: "Category" },
    { key: "subCategory", label: "SubCategory" },
    { key: "amount", label: "Amount" },
    { key: "paymentMethod", label: "Payment Method" },
    { key: "expenseDate", label: "Expense Date" },
    { key: "submissionDate", label: "Submission Date" },
    { key: "status", label: "Status" },
    { key: "actions", label: "Actions" },
  ],
  DATA_PAGE_TABLE_HEADER: [
    { header: "Name", key: "categoryName" },
    { header: "ActualMTD", key: "actualMTD" },
    { header: "BudgetMTD", key: "budgetMTD" },
    { header: "Variance", key: "variance" },
    { header: "CommentCount", key: "commentCounts" },
    { header: "BudgetMTH", key: "budgetMTH" },
    { header: "VarianceMTH", key: "varianceMTH" },
    { header: "ForecastMTH", key: "forecastMTH" },
  ],
  ROOMDATA_PAGE_TABLE_HEADER: [
    { label: "Sr NO.", key: "srNo" },
    { label: "Created Date", key: "isoDate" },
    { label: "Room Counts", key: "roomsCount" },
    { label: "Description", key: "description" },
    { label: "Created By", key: "createdBy" },
    { label: "Modified By", key: "modifiedBy" },
    { label: "Actions", key: "actions" },
  ],
  PROPERTYDATA_PAGE_TABLE_HEADER: [
    { label: "Budget", key: "departmentTotalBudget" },
    { label: "A+B", key: "ab" },
    { label: "TTM", key: "ttm" },
  ],
  MONTHLY_REPORT_TABLE_HEADER: [
    { key: "Month", label: "Month" },
    { key: "approverNames", label: "Approver" },
    { key: "formStatus", label: "Form Status" },
    { key: "status", label: "Status" },
    { key: "commentCount", label: "Comment Count" },
  ],
  CAPEX_PAGE_TABLE_HEADER: [
    { key: "srNo", label: "Sr No." },
    { key: "propertyName", label: "Property Name" },
    { key: "projectName", label: "Project Name" },
    { key: "invoiceDate", label: "Expense Date" },
    { key: "postDate", label: "Post Date" },
    { key: "vendorName", label: "Vendor" },
    { key: "invoiceNumber", label: "Invoice Number" },
    { key: "invoiceType", label: "Type" },
    { key: "invoiceAmount", label: "Cost" },
    { key: "description", label: "Description" },
    { key: "approverName", label: "Approver" },
    { key: "approvalStatus", label: "Approval Status" },
    { key: "expenseCommentCount", label: "Comment" },
  ],
  USER_PROFILE_PAGE_TABLE_HEADER: [
    { key: "srNo", label: "Sr No" },
    { key: "firstName", label: "First Name" },
    { key: "lastName", label: "Last Name" },
    { key: "fullName", label: "Full Name" },
    { key: "email", label: "Email" },
    { key: "phoneNumber", label: "Phone Number" },
    { key: "alternatePhoneNumber", label: "Alternate Phone Number" },
    { key: "gender", label: "Gender" },
    { key: "dateOfBirth", label: "Birth Date" },
    { key: "companyName", label: "Company Name" },
    { key: "department", label: "Department" },
    { key: "designation", label: "Designation" },
    { key: "employeeId", label: "Employee Id" },
    { key: "city", label: "City" },
    { key: "state", label: "State" },
    { key: "country", label: "Country" },
    { key: "zipcode", label: "Zipcode" },
    { key: "district", label: "District" },
    { key: "username", label: "Username" },
    { key: "website", label: "Website" },
    { key: "status", label: "Status" },
    { key: "profileImage", label: "Profile Image" },
    { key: "description", label: "Description" },
    { key: "notes", label: "Notes" },
    { key: "createdBy", label: "Created By" },
    { key: "updatedBy", label: "Updated By" },
    { key: "operations", label: "Operations" },
  ],
  PAYROLL_PAGE_TABLE_HEADER: [
    { key: "srNo", header: "Sr No" },
    { key: "categoryName", header: "Category Name" },
    { key: "accountNumber", header: "Account Number" },
    { key: "departmentType", header: "Department Type" },
    { key: "actualMTD", header: "ActualMTD" },
    { key: "budgetMTD", header: "BudgetMTD" },
    { key: "variance", header: "Varience" },
    { key: "forecastMTH", header: "ForcastNTH" },
    { key: "budgetMTH", header: "BudgetMTh" },
    { key: "varianceMTH", header: "VarienceMTH" },
    { key: "commentCount", header: "CommentCount" },
  ],
};
