export const CONSTANT = {
  SUCCESS: {
    CREATE: "Data created successfully",
    UPDATE: "Data updated successfully",
    DELETE: "Data deleted successfully",
    FETCH: "Data fetched successfully",
    LOGOUT: "User LogOut successfully",
    LOGIN: "User LogIn successfully",
  },
  ERROR: {
    NETWORK: "Network error, please try again",
    NOT_FOUND: "Data not found",
    COMMON: "Something Went Wrong!",
    LARGE_IMAGE_FILE: "File size must be less than 5 MB",
    LARGE_VIDEO_FILE: "File size must be less than 10 MB",
    DATA_NOT_SELECTED: "Please Select a Data",
    PREVIEW_FAIL: "File Preview Fail",
  },
  MIME_TYPES: {
    IMAGE: ["image/jpg", "image/png", "image/jpeg", "image/webp"],
    PDF: "application/pdf",
    EXCEL: [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-excel",
    ],
    VIDEO: [
      "video/mp4",
      "video/webm",
      "video/ogg",
      "video/x-matroska",
      "video/mkv",
      "video/matroska",
    ],
  },
  VALIDATION: {
    EMAIL: "Email is required!",
    FIRSTNAME: "First Name is required!",
    LASTNAME: "Last Name is required!",
    FULLNAME: "Full Name is required!",
    PHONENUMBER: "Phone Number is required!",
    ALTERNATEPHONENUMBER: "Alternate Phone Number is required!",
    GENDER: "Gender is required!",
    DATEOFBIRTH: "Date of Birth is required!",
    COMPANYNAME: "Company Name is required!",
    DEPARTMENT: "Department is required!",
    DESIGNATION: "Designation is required!",
    EMPLOYEEID: "Employee ID is required!",
    CITY: "City is required!",
    STATE: "State is required!",
    COUNTRY: "Country is required!",
    ZIPCODE: "Zipcode is required!",
    DISTRICT: "District is required!",
    USERNAME: "Username is required!",
    PASSWORD: "Password is required!",
    CONFIRMPASSWORD: "Confirm Password is required!",
    WEBSITE: "Website is required!",
    DESCRIPTION: "Description is required!",
    NOTES: "Notes are required!",
    STATUS: "Status is required!",
    PROFILEIMAGE: "Profile Image is required!",
    CREATEDBY: "Created By is required!",
    UPDATEDBY: "Updated By is required!",
  },
  MAX_FILE_SIZE: {
    SMALL: 5 * 1024 * 1024,
    LARGE: 10 * 1024 * 1024,
  },
};
